# -*- coding: utf-8 -*-
"""software now question 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1323FkydMLtSvpyAjGVS_PC6J6fLqhn4j
"""

from google.colab import files


uploaded = files.upload()

# Simple text encryption and decryption program
import string

# Alphabets
lowercase = string.ascii_lowercase
uppercase = string.ascii_uppercase

# ---------------- Encrypt Function ----------------
def encrypt_text(input_file, output_file, shift1, shift2):
    with open(input_file, 'r', encoding='latin-1') as f:
        text = f.read().replace('\r\n', '\n')

    encrypted = ""
    for char in text:
        if char in lowercase:
            if char <= 'm':  # first half
                index = lowercase.index(char)
                new_index = (index + shift1 * shift2) % 26
                new_char = lowercase[new_index]
            else:  # second half
                index = lowercase.index(char)
                new_index = (index - shift1 * shift2) % 26
                new_char = lowercase[new_index]
        elif char in uppercase:
            if char <= 'M':  # first half
                index = uppercase.index(char)
                new_index = (index - shift1) % 26
                new_char = uppercase[new_index]
            else:  # second half
                index = uppercase.index(char)
                new_index = (index + shift2**2) % 26
                new_char = uppercase[new_index]
        else:
            new_char = char
        encrypted += new_char  # inside loop

    with open(output_file, 'w', encoding='latin-1') as f:
        f.write(encrypted)
    print("Encryption done. Check the file:", output_file)

# ---------------- Decrypt Function ----------------
def decrypt_text(input_file, output_file, shift1, shift2):
    with open(input_file, 'r', encoding='latin-1') as f:
        text = f.read().replace('\r\n', '\n')

    decrypted = ""
    for char in text:
        if char in lowercase:
            if char <= 'm':  # first half
                index = lowercase.index(char)
                new_index = (index - shift1 * shift2) % 26
                new_char = lowercase[new_index]
            else:  # second half
                index = lowercase.index(char)
                new_index = (index + shift1 * shift2) % 26
                new_char = lowercase[new_index]
        elif char in uppercase:
            if char <= 'M':  # first half
                index = uppercase.index(char)
                new_index = (index + shift1) % 26
                new_char = uppercase[new_index]
            else:  # second half
                index = uppercase.index(char)
                new_index = (index - shift2**2) % 26
                new_char = uppercase[new_index]
        else:
            new_char = char
        decrypted += new_char  # inside loop

    with open(output_file, 'w', encoding='latin-1') as f:
        f.write(decrypted)
    print("Decryption done. Check the file:", output_file)

# ---------------- Verify Function ----------------
def verify(original_file, decrypted_file):
    with open(original_file, 'r', encoding='latin-1') as f:
        original = f.read().replace('\r\n', '\n')
    with open(decrypted_file, 'r', encoding='latin-1') as f:
        decrypted = f.read().replace('\r\n', '\n')

    if original == decrypted:
        print("The decrypted text matches the original perfectly :)")
    else:
        print("Oops! The decrypted text does not match.")

# ---------------- Main Program ----------------
print("Let's encrypt and decrypt a text file")

shift1 = int(input("Place a number for shift1: "))
shift2 = int(input("Place a number for shift2: "))

input_file = "raw_text.txt"
encrypted_file = "encrypted_text.txt"
decrypted_file = "decrypted_text.txt"

encrypt_text(input_file, encrypted_file, shift1, shift2)
decrypt_text(encrypted_file, decrypted_file, shift1, shift2)
verify(input_file, decrypted_file)

from google.colab import files
files.download('encrypted_text.txt')
files.download('decrypted_text.txt')